version: "3.9"
services:
  # DB RAW
  mysql:
    image: mysql:8.0
    container_name: project1-mysqlDB
    restart: unless-stopped
    ports: ["3306:3306"]
    env_file: [.env]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5
    container_name: project1-phpmyadmin
    restart: unless-stopped
    ports: ["8081:80"]    
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on: [mysql]

  # DB TRANSFORMED
  postgres-dw:
    image: postgres:16
    container_name: project1-postgresqlDB
    restart: unless-stopped
    ports: ["5432:5432"]
    env_file: [.env]
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: project1-pgadmin
    restart: unless-stopped
    ports: ["8080:80"]    
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on: [postgres-dw]

volumes:
  mysql_data:
  pg_data:

