version: "3.9"
services:

  
  # DB DW
  postgres-dw:
    image: postgres:16
    container_name: project2-postgresqlDB
    restart: unless-stopped
    ports: ["5433:5432"]
    env_file: [.env]
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: project2-pgadmin
    restart: unless-stopped
    ports: ["8080:80"]    
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on: [postgres-dw]

volumes:
  pg_data:
